# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY METAPACK.NVIM!!!
# YOU SHOULD NOT EDIT THIS FILE, INSTEAD EDIT YOUR METAPACK.NVIM CONFIGURATION!!!


{ pkgs, inputs, ... }: {
    environment.systemPackages = with pkgs; [
        clang-tools
        lua-language-server
        bash-language-server
        ltex-ls-plus
        yaml-language-server
        stylua
        nil
        alejandra
        black
    ];
}
