export ARCH
export P
export PN
export PV
export PR
export PVR
export PF
export CATEGORY
export A
export WORKDIR
export FILESDIR
export EBUILD_PHASE
export EBUILD_PHASE_FUNC
export EPREFIX
export S
export T
export D
export ED
export MERGE_TYPE
export PROVIDES_EXCLUDE
export PORTAGE_LOG_FILE
export PORTAGE_SOCKS5_PROXY
export REPLACED_BY_VERSION
export REPLACING_VERSIONS
export REQUIRES_EXCLUDE
export ROOT
export EROOT
export BROOT
export DESCRIPTION
#shellcheck disable=SC2034
export EAPI
export SRC_URI
export HOMEPAGE
export KEYWORDS
export SLOT
export LICENSE
export IUSE
export DEPEND
export RDEPEND
export BDEPEND
export IDEPEND
export PDEPEND
export REQUIRED_USE
export RESTRICT
export PROPERTIES
export DOCS
export PATCHES
