return {
    "nvim-treesitter/nvim-treesitter-textobjects",
    main = "nvim-treesitter.configs",
    config = {
        textobjects = {
            select = {
                enable = true,
                lookahead = true,
                keymaps = {
                    ["af"] = { query = "@function.outer", desc = "Function" },
                    ["if"] = { query = "@function.inner", desc = "Function" },
                    ["ac"] = { query = "@class.outer", desc = "Class" },
                    ["ic"] = { query = "@class.inner", desc = "Class" },
                    ["al"] = { query = "@loop.outer", desc = "Loop" },
                    ["il"] = { query = "@loop.inner", desc = "Loop" },
                    ["aa"] = { query = "@assignment.outer", desc = "Assignment" },
                    ["ia"] = { query = "@assignment.inner", desc = "Assignment" },
                    ["H"] = { query = "@assignment.lhs", desc = "Assignment LHS" },
                    ["L"] = { query = "@assignment.rhs", desc = "Assignment RHS" },
                    ["ar"] = { query = "@regex.outer", desc = "Regex" },
                    ["ir"] = { query = "@regex.inner", desc = "Regex" },
                    ["aR"] = { query = "@return.outer", desc = "Return" },
                    ["iR"] = { query = "@return.inner", desc = "Return" },
                },
                selection_modes = {
                    ["@parameter.outer"] = "v", -- charwise
                    ["@function.outer"] = "V", -- linewise
                    ["@class.outer"] = "<c-q>", -- blockwise
                },
                include_surrounding_whitespace = true,
            },
        },
    },
    dependencies = {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        main = "nvim-treesitter.configs",
        config = {
            ensure_installed = {
                "awk",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "comment",
                "commonlisp",
                "cpp",
                "css",
                "csv",
                "cuda",
                "desktop",
                "diff",
                "disassembly",
                "dockerfile",
                "dot",
                "doxygen",
                "ebnf",
                "editorconfig",
                "fish",
                "forth",
                "fsharp",
                "gdscript",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "glsl",
                "gn",
                "go",
                "goctl",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "gpg",
                "graphql",
                "haskell",
                "haskell_persistent",
                "hjson",
                "hlsl",
                "hlsplaylist",
                "html",
                "http",
                "hurl",
                "hyprlang",
                "ini",
                "ispc",
                "java",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "llvm",
                "lua",
                "luadoc",
                "luap",
                "luau",
                "make",
                "markdown",
                "markdown_inline",
                "meson",
                "muttrc",
                "nginx",
                "objdump",
                "ocaml",
                "ocaml_interface",
                "pascal",
                "passwd",
                "perl",
                "php",
                "powershell",
                "printf",
                "properties",
                "python",
                "query",
                "regex",
                "sql",
                "ssh_config",
                "sway",
                "toml",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "yuck",
                "zathurarc",
                "zig",
                -- "gdresource",
                -- "hex",
            },
            sync_install = false,
            auto_install = false,
            highlight = {
                enable = true,
            },
        },
    },
}
