#!/usr/bin/env bash

terminal=foot
waybar="waybar --config $HOME/.config/shitbox/configs/programs/waybar/config/river.json --style $HOME/.config/shitbox/configs/programs/waybar/config/style.css"

riverctl spawn $HOME/.config/shitbox/scripts/startup.sh "$waybar"

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

riverctl map normal\
    Super Q\
    spawn "
        riverctl\
            rule-add\
            -title $terminal\
            fullscreen\
        &&
        $terminal\
        -e \"$HOME/.config/hypr/scripts/autostart-tmux.sh\"\
        && {
            sleep 1;
            riverctl\
                rule-del\
                -title $terminal\
                fullscreen;
        }
    "
riverctl map normal Super+Shift escape close
riverctl map normal Super R spawn "$HOME/.config/shitbox/scripts/menu.sh $terminal"
riverctl map normal Alt F4 spawn "$HOME/.config/hypr/scripts/shutdown.sh"

riverctl map normal Super h focus-view left
riverctl map normal Super j focus-view down
riverctl map normal Super k focus-view up
riverctl map normal Super l focus-view right

# Super+J and Super+K to focus the next/previous view in the layout stack
# riverctl map normal Super J focus-view next
# riverctl map normal Super K focus-view previous
#
# # Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# # view in the layout stack
# riverctl map normal Super+Shift J swap next
# riverctl map normal Super+Shift K swap previous
#
# # Super+Period and Super+Comma to focus the next/previous output
# riverctl map normal Super Period focus-output next
# riverctl map normal Super Comma focus-output previous
#
# # Super+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal Super+Shift Period send-to-output next
# riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map normal Super+Shift V toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super tab set-focused-tags $all_tags

riverctl map normal Super f11 toggle-fullscreen

riverctl map -repeat normal Super equal spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"
riverctl map -repeat normal Super minus spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"

# Super+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "Pinentry-gtk" float

riverctl rule-add ssd
riverctl default-layout wideriver
# start layout manager
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --no-smart-gaps                            \
    --inner-gaps                   0           \
    --outer-gaps                   0           \
    --border-width                 2           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      0           \
    --border-color-focused         "0xff00ff"  \
    --border-color-focused-monocle "0x586e75"  \
    --border-color-unfocused       "0x850045"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

riverctl send-layout-cmd wideriver "--layout left --stack dwindle --count 1 --ratio 0.5"

riverctl focus-follows-cursor normal
